create table MJMEMBER
(
    USERNAME NVARCHAR2(50),
    PASSWORD NVARCHAR2(50),
    MNAME NVARCHAR2(50),
    MBIRTH NVARCHAR2(50),
    MEMAIL NVARCHAR2(50),
    MADDR NVARCHAR2(50),
    MFILENAME NVARCHAR2(50)
);